/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1_admin (void);
GtkWidget* create_window2_admin (void);
GtkWidget* create_window3_admin (void);
GtkWidget* create_window4_admin (void);
GtkWidget* create_window5_admin (void);
GtkWidget* create_window7_admin (void);
GtkWidget* create_window8_admin (void);
GtkWidget* create_window9_admin (void);
GtkWidget* create_window10_admin (void);
GtkWidget* create_window12_admin (void);
GtkWidget* create_window13_admin (void);
GtkWidget* create_window14_admin (void);
