/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_authentification (void);
GtkWidget* create_window_getion_medecin (void);
GtkWidget* create_window_fiche_medicale_medecin (void);
GtkWidget* create_window_ajouter_fiche_medicale_medecin (void);
GtkWidget* create_window_rendez_vous_medecin (void);
GtkWidget* create_window_modifier_fiche_medicale_medecin (void);
GtkWidget* create_window_supprimer_fiche_medicale_medecin (void);
GtkWidget* create_window_disponibilites_medecin (void);
GtkWidget* create_window_ajouter_disponibilites_medecin (void);
GtkWidget* create_window_modifier_disponibilites_medecin (void);
GtkWidget* create_window_supprimer_disponibilites_medecin (void);
